### PR TITLE
GPSS Fixes + Language Upgrades

### PR DESCRIPTION
**Pull request by FM1337**
Updated GPSS stuff to work with upcoming version of GPSS + also updated the language system.

### CODE REVIEW

**Review by piepie62 — APPROVED** [review]
Looks pretty much good

**Review by LiquidFenrir — APPROVED** [review]
don't see any issue in this

**Comment by FM1337** [comment]
perfect thanks mates.

**Comment by FM1337** [comment]
test

**Comment by FM1337** [comment]
Merging this in now, site is live, don't kill me @piepie62

**Pull request merged**
