### PR TITLE
Add decoders for the SoundStuff branch

### PR DESCRIPTION
**Pull request by Oreo639**
These are my changes to the soundstuff branch.
It isn't ready to merge (which is why it is a draft pr rn). 
I'm making this so it is easier to track the changes between the fork and the main repo.

The main issues are that libopus and dr_flac crash for some reason. Everything else appears to work fine. I have no idea what is causing it. I'll see if I can look into it further when I am available to do so.

Ofc feel free to leave comments.

### CODE REVIEW

**Comment by BernardoGiordano** [comment]
Is flac/opus support really necessary?

**Comment by Oreo639** [comment]
No, I don't think they were supported before. But I would still like to find out what is causing the crash (in case it could cause problems in the future).

**Comment by piepie62** [comment]
Despite the fact that effects are not working for whatever strange reason, I think the main purpose of this PR has been filled: getting rid of the dependency on SDL. Eventually, we may figure out what's wrong with effects, but for now I'd like to get the current improvements in.

**Comment by piepie62** [comment]
Could you switch to using std::make_shared instead of the shared_ptr constructor, and remove the Vorbis decoder? I'd rather not have OGG Vorbis support but not OGG Opus support; that's a great recipe for user confusion

**Comment by Oreo639** [comment]
> I'd rather not have OGG Vorbis support but not OGG Opus support; that's a great recipe for user confusion

Just so you know, that is the current behavior in 3ds-sdl_mixer.
<https://github.com/devkitPro/pacman-packages/blob/master/3ds/SDL_mixer/PKGBUILD>

**Comment by piepie62** [comment]
As of the latest commit, effects are now fixed

**Pull request merged**
