### PR TITLE
G.P.S.S, Automatic Updater, and some bug fixes

### PR DESCRIPTION
**Pull request by FM1337**
As per our brief discussion on discord, I cleaned up what I could think of, and if I missed anything or if anything needs to be further improved/cleaned up please let me know.

### CODE REVIEW

**Comment by piepie62** [comment]
Auto updater works perfectly, replacing the current 3dsx or replacing the title

**Comment by FM1337** [comment]
@BernardoGiordano this should now be good to merge

**Comment by piepie62** [comment]
Updated to be compatible with master branch

**Comment by FM1337** [comment]
@piepie62 after you merged whatever you did, PKSM now crashes at the "loading storage" screen on bootup.

**Comment by FM1337** [comment]
@BernardoGiordano It appears that the fix that @piepie62 has commited, should be the final change needed to merge this with the master branch of PKSM

**Pull request merged**
